name: Build and Release

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout кода
      uses: actions/checkout@v4

    - name: Установка .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Восстановление зависимостей
      run: dotnet restore

    - name: Сборка и публикация (self-contained .exe)
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true ^
          -p:PublishSingleFile=true ^
          -p:IncludeAllContentForSelfExtract=true ^
          -p:PublishTrimmed=true ^
          -p:DebugType=None ^
          -p:AssemblyVersion=${{ github.run_number }}.^
          -p:FileVersion=${{ github.run_number }}.0

    - name: Подготовка артефактов
      run: |
        cd bin/Release/net6.0-windows/win-x64/publish/
        7z a ../../../../../SharpVLESS.zip *.exe *.dll config.json
        cd ../../../..
        mkdir ReleaseArtifacts
        move bin/Release/net6.0-windows/win-x64/publish/*.exe ReleaseArtifacts/SharpVLESS.exe
        move SharpVLESS.zip ReleaseArtifacts/

    - name: Загрузка артефактов
      uses: actions/upload-artifact@v3
      with:
        path: ReleaseArtifacts/

    - name: Создание релиза (если тег)
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ReleaseArtifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Установка WiX Toolset (для MSI)
      run: |
        choco install wixtoolset -y
      shell: cmd

    - name: Сборка MSI установщика
      run: |
        mkdir -p wix/Project
        cp bin/Release/net6.0-windows/win-x64/publish/*.exe wix/Project/
        cp Resources/app.ico wix/Project/ 2>nul || echo "Иконка не найдена"
        |
        # Пример простого .wxs (можно вынести в репо)
        cat > wix/Product.wxs << EOF
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" Name="SharpVLESS" Language="1033" Version="1.0.0" Manufacturer="Me" UpgradeCode="a1b2c3d4-a1b2-a1b2-a1b2-a1b2c3d4e5f6">
    <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
    <MajorUpgrade DowngradeErrorMessage="Новая версия уже установлена." />
    <MediaTemplate />
    <Feature Id="MainFeature" Title="SharpVLESS" Level="1">
      <ComponentGroupRef Id="ProductComponents" />
    </Feature>
  </Product>
  <Fragment>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="SharpVLESS" />
      </Directory>
    </Directory>
  </Fragment>
  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
      <Component Id="SharpVLESS.exe" Guid="a1b2c3d4-a1b2-a1b2-a1b2-a1b2c3d4e5f7">
        <File Source="Project\SharpVLESS.exe" KeyPath="yes" />
      </Component>
    </ComponentGroup>
  </Fragment>
</Wix>
EOF
        candle.exe wix/Product.wxs -dPlatform=x64
        light.exe -ext WixUIExtension Product.wixobj -o SharpVLESS-Setup.msi
        mv SharpVLESS-Setup.msi ReleaseArtifacts/

    - name: Обновление релиза с MSI
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ReleaseArtifacts/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true