# .github/workflows/build-all.yml

name: Build Cross-Platform Releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish Self-Contained Win-x64
        run: |
          dotnet publish -c Release \
            -r win-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o ./publish

      - name: Zip Artifact
        run: |
          Compress-Archive -Path "./publish/*" -DestinationPath "sharp-vless-windows-x64.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sharp-vless-windows-x64
          path: sharp-vless-windows-x64.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sharp-vless-windows-x64.zip
          asset_name: sharp-vless-windows-x64.zip
          tag: ${{ github.ref }}
          overwrite: true

  build-linux:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish Self-Contained Linux-x64
        run: |
          dotnet publish -c Release \
            -r linux-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -p:EnableCompressionInSingleFile=true \
            -o ./publish

      - name: Make executable
        run: |
          chmod +x ./publish/sharp-vless

      - name: Tar Artifact
        run: |
          tar -czf sharp-vless-linux-x64.tar.gz -C ./publish .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sharp-vless-linux-x64
          path: sharp-vless-linux-x64.tar.gz

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sharp-vless-linux-x64.tar.gz
          asset_name: sharp-vless-linux-x64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  build-macos:
    name: Build macOS x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish Self-Contained macOS-x64
        run: |
          dotnet publish -c Release \
            -r osx-x64 \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -p:EnableCompressionInSingleFile=true \
            -o ./publish

      - name: Make executable
        run: |
          chmod +x ./publish/sharp-vless

      - name: Tar Artifact
        run: |
          tar -czf sharp-vless-macos-x64.tar.gz -C ./publish .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sharp-vless-macos-x64
          path: sharp-vless-macos-x64.tar.gz

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sharp-vless-macos-x64.tar.gz
          asset_name: sharp-vless-macos-x64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
